/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SimulatorMomentumRouteImport } from './routes/simulator/momentum'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SimulatorMomentumRoute = SimulatorMomentumRouteImport.update({
  id: '/simulator/momentum',
  path: '/simulator/momentum',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/simulator/momentum': typeof SimulatorMomentumRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/simulator/momentum': typeof SimulatorMomentumRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/simulator/momentum': typeof SimulatorMomentumRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/simulator/momentum'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/simulator/momentum'
  id: '__root__' | '/' | '/simulator/momentum'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SimulatorMomentumRoute: typeof SimulatorMomentumRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/simulator/momentum': {
      id: '/simulator/momentum'
      path: '/simulator/momentum'
      fullPath: '/simulator/momentum'
      preLoaderRoute: typeof SimulatorMomentumRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SimulatorMomentumRoute: SimulatorMomentumRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
